// <auto-generated />
using System;
using ItEquipmentCheckout.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ItEquipmentCheckout.Web.Data.Migrations
{
    [DbContext(typeof(CheckoutDbContext))]
    [Migration("20260730010829_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("ItEquipmentCheckout.Core.Entities.Checkout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ActualReturnDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CheckoutDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PlannedReturnDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("EquipmentId")
                        .IsUnique()
                        .HasFilter("\"ActualReturnDate\" IS NULL");

                    b.HasIndex("PlannedReturnDate");

                    b.HasIndex("EquipmentId", "ActualReturnDate");

                    b.ToTable("Checkouts", t =>
                        {
                            t.HasCheckConstraint("CK_Checkout_ActualReturnDate", "\"ActualReturnDate\" IS NULL OR \"ActualReturnDate\" >= \"CheckoutDate\"");

                            t.HasCheckConstraint("CK_Checkout_PlannedReturnDate", "\"PlannedReturnDate\" >= \"CheckoutDate\"");
                        });
                });

            modelBuilder.Entity("ItEquipmentCheckout.Core.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("EmployeeNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EmployeeNumber")
                        .IsUnique();

                    b.HasIndex("FullName");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("ItEquipmentCheckout.Core.Entities.Equipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExpectedReturnDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InventoryNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InventoryNumber")
                        .IsUnique();

                    b.HasIndex("SerialNumber")
                        .IsUnique();

                    b.HasIndex("Status", "Category");

                    b.ToTable("Equipment", t =>
                        {
                            t.HasCheckConstraint("CK_Equipment_ExpectedReturnDays", "\"ExpectedReturnDays\" BETWEEN 1 AND 365");
                        });
                });

            modelBuilder.Entity("ItEquipmentCheckout.Core.Entities.EquipmentEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CheckoutId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CheckoutId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("EquipmentId", "OccurredAt");

                    b.ToTable("EquipmentEvents");
                });

            modelBuilder.Entity("ItEquipmentCheckout.Core.Entities.Checkout", b =>
                {
                    b.HasOne("ItEquipmentCheckout.Core.Entities.Employee", "Employee")
                        .WithMany("Checkouts")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ItEquipmentCheckout.Core.Entities.Equipment", "Equipment")
                        .WithMany("Checkouts")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("ItEquipmentCheckout.Core.Entities.EquipmentEvent", b =>
                {
                    b.HasOne("ItEquipmentCheckout.Core.Entities.Checkout", "Checkout")
                        .WithMany()
                        .HasForeignKey("CheckoutId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ItEquipmentCheckout.Core.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ItEquipmentCheckout.Core.Entities.Equipment", "Equipment")
                        .WithMany("Events")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Checkout");

                    b.Navigation("Employee");

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("ItEquipmentCheckout.Core.Entities.Employee", b =>
                {
                    b.Navigation("Checkouts");
                });

            modelBuilder.Entity("ItEquipmentCheckout.Core.Entities.Equipment", b =>
                {
                    b.Navigation("Checkouts");

                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
